trigger:
- main  # This will trigger the pipeline on commits to the main branch

pool:
  vmImage: 'windows-latest'  # Use Windows as the build agent

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Based on our earlier conversation, you are using .NET 8
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build ServerlessAPI.csproj --configuration Release
  displayName: 'Build Project'

- script: |
    dotnet publish ServerlessAPI.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Project'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'AzureSPConnection'  # Your Azure subscription connection name
    appType: 'functionApp'
    appName: 'MyServerlessAPI'  # Your Function App name
    package: '$(Build.ArtifactStagingDirectory)'
